list.exe : main.o contact.o list.o
	gcc main.o contact.o list.o -g -o list.exe

main.o : main.c
	gcc main.c -g -c -o main.o

contact.o : contact.c
	gcc contact.c -g -c -o contact.o

list.o : list.c
	gcc list.c -g -c -o list.o

