tree.exe : main.o contact.o tree.o
	gcc main.o contact.o tree.o -g -o tree.exe

main.o : main.c
	gcc main.c -g -c -o main.o

contact.o : contact.c
	gcc contact.c -g -c -o contact.o

tree.o : tree.c
	gcc tree.c -g -c -o tree.o

